services:
  - type: web
    name: intersitesdigital
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_URI_DIRECT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false